In [61]:
import pandas as pd
import numpy as np

In [62]:
needed_features = [' id ',' gaze_0_x',' gaze_0_y',' gaze_1_x',' gaze_1_y',' gaze_angle_x',' gaze_angle_y',' AU01_c',' AU02_c',' AU04_c',' AU05_c',' AU06_c',' AU07_c',' AU09_c',' AU10_c',' AU12_c',' AU14_c',' AU15_c',' AU17_c',' AU20_c',' AU23_c',' AU25_c',' AU26_c',' AU28_c',' AU45_c',' AU01_r',' AU02_r',' AU04_r',' AU07_r',' AU09_r',' AU12_r',' AU14_r',' AU15_r',' AU17_r',' AU20_r',' AU23_r',' AU25_r',' AU26_r','QoE']

In [63]:
pickle1 = pd.read_pickle("dataset/pickle1")
pickle1 = pickle1.filter(needed_features)
pickle2 = pd.read_pickle("dataset/pickle2")
pickle2 = pickle2.filter(needed_features)
pickle3 = pd.read_pickle("dataset/pickle3")
pickle3 = pickle3.filter(needed_features)
pickle4 = pd.read_pickle("dataset/pickle4")
pickle4 = pickle4.filter(needed_features)
pickle5 = pd.read_pickle("dataset/pickle5")
pickle5 = pickle5.filter(needed_features)
pickle6 = pd.read_pickle("dataset/pickle6")
pickle6 = pickle6.filter(needed_features)
pickle7 = pd.read_pickle("dataset/pickle7")
pickle7 = pickle7.filter(needed_features)
pickle8 = pd.read_pickle("dataset/pickle8")
pickle8 = pickle8.filter(needed_features)
pickle9 = pd.read_pickle("dataset/pickle9")
pickle9 = pickle9.filter(needed_features)
pickle10 = pd.read_pickle("dataset/pickle10")
pickle10 = pickle10.filter(needed_features)

In [64]:
frames = [pickle1,pickle2,pickle3,pickle4,pickle5,pickle6,pickle7,pickle8,pickle9,pickle10]

In [65]:
complete_dataset = pd.concat(frames)

In [66]:
complete_dataset.to_pickle("complete_dataset")

In [67]:
complete_dataset = pd.read_pickle("complete_dataset")
complete_dataset

,id,gaze_0_x,gaze_0_y,gaze_1_x,gaze_1_y,gaze_angle_x,gaze_angle_y,AU01_c,AU02_c,AU04_c,...,AU09_r,AU12_r,AU14_r,AU15_r,AU17_r,AU20_r,AU23_r,AU25_r,AU26_r,QoE
0,1,0.082010,0.062940,-0.124776,0.080031,-0.022,0.072,0,0,0,...,0.00,0.0,0.00,0.00,0.08,0.00,0.36,0.77,1.29,2
1,1,0.078303,0.060465,-0.128854,0.077414,-0.025,0.069,0,0,0,...,0.00,0.0,0.00,0.00,0.13,0.00,0.29,0.66,1.18,2
2,1,0.080084,0.059067,-0.130403,0.076090,-0.025,0.068,0,0,0,...,0.00,0.0,0.00,0.00,0.21,0.00,0.30,0.54,1.06,2
3,1,0.081053,0.058107,-0.129042,0.074312,-0.024,0.067,0,0,0,...,0.00,0.0,0.00,0.00,0.14,0.00,0.22,0.60,1.00,2
4,1,0.082496,0.059614,-0.128192,0.076915,-0.023,0.069,0,0,0,...,0.00,0.0,0.00,0.00,0.10,0.00,0.23,0.58,1.00,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67392,400,0.057415,-0.149977,-0.143566,-0.121270,-0.044,-0.137,0,0,0,...,0.49,0.0,0.39,1.31,0.63,0.19,0.73,0.00,0.55,2
67393,400,0.057313,-0.149406,-0.143716,-0.120715,-0.044,-0.136,0,0,0,...,0.47,0.0,0.44,1.29,0.64,0.20,0.75,0.00,0.48,2
67394,400,0.057270,-0.148547,-0.143747,-0.119794,-0.044,-0.135,0,0,0,...,0.45,0.0,0.48,1.30,0.62,0.20,0.75,0.00,0.52,2
67395,400,0.056576,-0.149564,-0.143961,-0.120783,-0.044,-0.136,0,0,0,...,0.45,0.0,0.51,1.34,0.59,0.20,0.75,0.00,0.54,2
67396,400,0.056668,-0.149601,-0.143986,-0.120848,-0.044,-0.136,0,0,0,...,0.47,0.0,0.55,1.38,0.55,0.24,0.75,0.00,0.57,2

In [68]:
AUr_features = [' id ', ' AU01_r', ' AU02_r', ' AU04_r', ' AU07_r',' AU09_r', ' AU12_r', ' AU14_r', ' AU15_r', ' AU17_r',' AU20_r', ' AU23_r', ' AU25_r', ' AU26_r']

In [69]:
AUc_features = [' id ',' AU01_c',' AU02_c',' AU04_c',' AU05_c',' AU06_c',' AU07_c',' AU09_c',' AU10_c',' AU12_c',' AU14_c',' AU15_c',' AU17_c',' AU20_c',' AU23_c',' AU25_c',' AU26_c',' AU28_c',' AU45_c']

In [70]:
AUr = pd.read_pickle("complete_dataset")
AUr = AUr.filter(AUr_features)

In [73]:
AUc = pd.read_pickle("complete_dataset")
AUc = AUc.filter(AUc_features)

In [71]:
AUr.to_pickle("AUr")

In [75]:
AUc.to_pickle("AUc")

In [20]:
GD = complete_dataset[[" id "," gaze_0_x"," gaze_0_y"," gaze_1_x"," gaze_1_y"," gaze_angle_x"," gaze_angle_y"]]

In [22]:
GD.to_pickle("GD")

In [23]:
_id = 1
QoE = pd.DataFrame()
dic = {}
tr = complete_dataset.set_index(" id ")
while _id<401:
    q = tr["QoE"][_id][:1][_id]
    dic[" id "] = _id
    dic["QoE"] = q
    QoE = QoE.append(dic,ignore_index=True)
    _id = _id+1

In [24]:
QoE = QoE.set_index(" id ")

In [26]:
QoE.to_pickle("QoE")